# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build & Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Generate settings.xml
      uses: s4u/maven-settings-action@v2.6.0
      with:
        servers: |
          [{
            "id": "byggserver",
            "username": "${env.NEXUS_USER}",
            "password": "${env.NEXUS_PASS}"
          }]
    - name: Check settings
      run: cat $HOME/.m2/settings.xml
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        overwrite-settings: false
    - name: Build with Maven
      run: mvn package

    - name: Publish to Apache Maven
      run: mvn deploy -P mahjonglogic && mvn deploy -P github
      env:
        GITHUB_TOKEN: ${{ github.token }}
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASS: ${{ secrets.NEXUS_PASS }}

    - name: Deploy JavaDoc
      uses: MathieuSoysal/Javadoc-publisher.yml@v2.3.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        javadoc-branch: master
        java-version: 11
        target-folder: apidocs
